config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   devise_for :users

   root 'homes#top'
   get 'home/about' => 'homes#about'
 #book用 
resources :books, only: [:create, :index, :show, :edit, :update, :destroy, :update]


#user用

resources :users, only: [:show, :edit, :update, :index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books, dependent: :destroy
         attachment :profile_image

   

  #sing up入力画面でIntroduction can't be blankのエラーが
  validates :name, presence: true, length: { in: 2..20 }  
  validates :introduction, length: { maximum: 50 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

  
  def after_sign_in_path_for(resource) 
   
    user_path(current_user)
  end




  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :authenticate_user!
before_action :correct_user, only: [:edit, :update]
  
  def correct_user
    @book = current_user.books.find_by(id: params[:id])
      unless @book
        redirect_to books_path
      end
  end

  def index
  	@books = Book.all
    @user = current_user
    @book = Book.new
    
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
      @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'You have updeted book successfully.'
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render "books/edit"
    end 
  end  

  def create
     @book = Book.new(book_params)
     @book.user_id = current_user.id
      if @book.save
        flash[:notice] = 'You have creatad book successfully.'
        redirect_to book_path(@book)
    else
        @user = current_user
        @books = Book.all
        render "books/index"
     end 
  end		

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to user_path(current_user)
  end 

  private
   def book_params
    params.require(:book).permit(:title, :body)
   end  


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate_user!

  
	def index
		@users = User.all
    @user = current_user
    @book = Book.new
  end	
  	
  def show
		@user = User.find(params[:id])
		@book = Book.new
		@books = @user.books
	end	



  def create
    @user = User.create(user_params)
    @user.save
  	redirect_to user_path(@user.id)
  end



  def edit
    if params[:id].to_i == current_user.id
  	  @user = User.find(params[:id])
    else 
      redirect_to user_path(current_user)
    end
  end



def update
      @user = current_user
    if @user.update(user_params)
      flash[:notice] = 'You have updeted user successfully.'
      redirect_to user_path(current_user) 
  else
      @user = current_user
       @users = User.all
      render "users/edit"  
    end     
end 





  # def update
  # 	@user = User.find(params[:id])
  #   if @user.update(user_params)
  #     redirect_to user_path(current_user)
  #   else
  #     render "edit"
  #   end 
  # end	


  # def destroy
  # 	@user = User.find(params[:id])
  # 	@user.destroy
  # 	redirect_to user_path(@user.id) 
  # end 
	

  private
   def user_params
		params.require(:user).permit(:name, :introduction, :profile_image)
   end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
	
<!--エラーメッセージ-->
	<% if @book.errors.any? %>
		<div id="error_explanation" class="alert alert-danger">
			<h3><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h3>
			<ul>
			 <% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
	 </div>
	<% end %>


<div class="body">
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">				
				<h1>Editing Book</h1>
				<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>
				<div class="field row">
					<div class="col-xs-12">
						<h4>Title</h4>
						<div class="col-xs-12">
				  	<%= f.text_field :title, class:"form-control col-xs-12" %>
					</div>	
				</div>
				<div class="field row">
					<h4>Option</h4>
					<div class="col-xs-12">
				  	
				  	<%= f.text_area :body, class:"form-control col-xs-12" %>
					</div>
				</div>
				<div class="field row">
					<div class="col-xs-12">
				  	<%= f.submit 'Update Book', class:"btn btn-primary col-xs-12" %>   
						<% end %>
					</div>
				</div>	
				<div class="field row">
					<div class="col-xs-12">
					<%= link_to 'Show', book_path(@book) %>|
					<%= link_to 'Back', books_path %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/books/index.html.erb
<body>
	<header>
		<title>Bookers</title>
	</header>
	
	<!--エラーメッセージ-->
				<% if @book.errors.any? %>
				  <div id="error_explanation" class="alert alert-danger">
				  	 <h3><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h3>
				    <ul>
				      <% @book.errors.full_messages.each do |message| %>
				        <li><%= message %></li>
				      <% end %>
				    </ul>
				  </div>
				<% end %>
				<!--ここまで-->
	



	 <div class="body">
	<!--プロフィール画面-->
			<div class="container">
				<div class="row">
					<!--User info-->
					<div class="profiles col-xs-3">
				  	<h2 class="profile-name">User info</h2> 
					  <p class="image"><%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "100x100", class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></p>  
						  <div class="name">
								<p>name</p>
								<p><%= @user.name %></p>
						  </div>	
						  <div class="introduction">
								<p>Introduction</p>	
								<p><%= @user.introduction %></p>
						  </div>			
							<%= link_to user_path(@user) do %>
								<i class="col-xs-12 btn btn-default glyphicon glyphicon-wrench"></i>
							<% end %>	
					<!--User info-->

				<!--投稿画面-->
						<h2>New book</h2>
						<%= form_for(@book) do |f| %>
							<div class="field">
								<h4>Title</h4>
						<%= f.text_field :title %>
							</div>
							<div class="field">
								<h4>Opinion</h4>
						<%= f.text_area :body %>
							</div>
							<br class="create"><%= f.submit 'Create Book' %></br>
						<% end %>
				</div>
				<!--col-xs-3ここまで-->

					<div class="Books col-xs-9">
						<h2 class="Books">Books</h2>
						<table>
							<thead>
								<tr>
									<th class="title">Title</th>
									<th class="opinion">Opinion</th>
								</tr>
							</thead>
							<tbody>	
								<% @books.each do |book| %>
									<tr> 
										<td><%= link_to user_path(book.user) do %>
											<%= attachment_image_tag book.user, :profile_image, format: 'jpeg', size: "40x40", class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></td>
											<% end %>
										<td><%=link_to book.title, book_path(book) %></td> 				
										<td><%= book.body %></td>													
									</tr>  
								<% end %>
							</tbody> 		  
						</table>
					</div>
					<!--ここまで-->	
					</div>
				</div>
			</div>
		</body>

app/views/books/show.html.erb
<body>
	<header>
		<title>Bookers</title>
	</header>
	
	 <div class="body">
	<!--プロフィール画面-->
		<div class="container">
			<div class="row">
				<div class="profiles col-xs-3">
			  	<h2 class="profile-name">User info</h2>
				  	<!--画像表示部分-->  
				  <p class="picture"><%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "100x100", class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></p>  
					  <div class="name">
							<p>name</p>
							<p><%= @user.name %></p>
					  </div>	
					  <div class="introduction">
							<p>Introduction</p>	
							<p><%= @user.introduction %></p>
					  </div>		
			  <!--プロフィール編集画面リンク-->
						<% if @user.id == current_user.id %>
								<%= link_to edit_user_path(@user) do %>
									<i class="col-xs-12 btn btn-default glyphicon glyphicon-wrench"></i>
								<% end %>
							<% else %>
								<%= link_to user_path(current_user) do %>
									<i class="col-xs-12 btn btn-default glyphicon glyphicon-wrench"></i>
								<% end %>	
						<% end %>		
	<!--ここまで-->
	<!--投稿画面-->
					
							<h2>New book</h2>
							<!-- form_for部分 -->
							<%= form_for(@book_new) do |f| %>
								<div class="field">
									<h4>Title</h4>
							<%= f.text_field :title %>
								</div>
								<div class="field">
									<h4>Opinion</h4>
							<%= f.text_area :body %>
								</div>
							<br class="create"><%= f.submit 'Create Book' %></br>
							<% end %>
						</div>
	<!--本一覧画面-->
					<div class="Books col-xs-9">
						<h2 class="Users">Book detail</h2>
						<table>
							<thead></thead>
							<tbody class="line">
								<tr> 			
									<td class="content"><%= link_to user_path(@user) do %>
										<%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "40x40", class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
										<%= link_to @user.name, user_path(@user) %>

										<% end %>
									</td>	
									<td class="content"><%= @book.title %></td>
									<td class="content"><%= @book.body %></td>
									<td>
										<% if @user == current_user %>
											<td class="btn-sm btn-success"><%= link_to "Edit", edit_book_path(@book) %></td>
											<td class="btn-sm btn-danger"><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？" %></td>
										<% end %>	
									</td>
								</tr>  
							</tbody>   
						</table>
					</div>
				</div>
			</div>
		</div>	
	</body>

app/views/homes/about.html.erb
<h1 class="top"><strong>Welcome to<i class="fas fa-book"></i> Bookers !!</strong></h1>	

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>


<div class="container">
	<div class="row">
		<div class="top-message col-md-offset-3 col-md6">
			 <h1 class="top"><strong>Welcome to<i class="fas fa-book"></i> Bookers !!</strong></h1>	
			 <p>In<i class="fas fa-book"></i> <strong>Bookers,</strong></p>
			 <p>you can share and exchange your opinions, inpressions , and emotions</p>
			 <p>about various books!</p>
		</div>
	</div>
	<div class="btn-wrapper">
		<div class="row">

			<%= link_to 'Log in', new_user_session_path, class: "btn btn-info col-xs-5 col-xs-offset-3" %>
		</div>
		<div class="row">	
			<%= link_to 'Sign up', new_user_registration_path, class: "btn btn-success col-xs-5 col-xs-offset-3" %> 
		</div>
	</div>
</div>


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <header class="navbar navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <br><span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
           <% if user_signed_in? %> 
            <li><a class="glyphicon glyphicon-home home" href= <%="/users/#{current_user.id}" %> >Home</a></li>
            <li><a class="glyphicon glyphicon-link about" href="/users">Users</a></li>
            <li><a class="glyphicon glyphicon-edit sign_up" href="/books">Books</a></li>
            <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %> </li>
       <% else %>
            <li><a class="glyphicon glyphicon-home home" href="/"> Home</a></li>
            <li><a class="glyphicon glyphicon-link about" href="/home/about">About</a></li>
            <li><a class="glyphicon glyphicon-edit sign_up" href="/users/sign_up">sign up</a></li>
            <li><a class="glyphicon glyphicon-log-in sign_in" href="/users/sign_in"> login</a></li>
        <% end %>
          </ul>
        </nav>
      </div>
    </header>   
    <!--サクセスメッセージ-->
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <!--ここまで-->
    <%= yield %>
   <footer>
     <div class="container">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-9">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>  
   </footer>   
  </body>
</html>

app/views/users/edit.html.erb
 <!--エラーメッセージ-->
  <% if @user.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
             <h3><%= pluralize(@user.errors.count, "error") %> prohibited this product from being saved:</h3>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
   <% end %>
  <!--エラーメッセージ-->

  <div class="body">
    <div class="container">
     <div class="row">
      <div class="profiles col-xs-3">
         <h1>User info</h1>
        <%= form_for(@user) do |f| %>
          
        <!--Name-->  
            <div class="field"> 
               <p><strong>Name</strong></p>
          	   <label class="control-label sr-only" for="inputName">Name</label>
          	   <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputName"%>
           	</div>
          <!--Image-->
            <div class="field"> 
            	 <p><strong>Image</strong></p>	
          	  <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
          	  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
            </div>
          <!--Introduction-->
            <div class="field"> 
              <p><strong>Introduction</strong></p>
              <label class="control-label sr-only" for="inputName">Introduction</label>
              <%= f.text_area :introduction, autofocus: true, class:"form-control", id:"inputArea"%>
            </div>  
    <!--submit-->
        <%= f.submit "Update User", class:"btn btn-light" %>
      <% end %>
    </div>
  </div>
 </div>
</div>

app/views/users/index.html.erb
<body>
	<header>
		<title>Bookers</title>
	</header>
	
	 <div class="body">
	 	<div class="container">
	 		<div class="row">
	<!--プロフィール画面-->
				<div class="profiles col-xs-3">
			  	<h2 class="profile-name">User info</h2>
				  	<!--画像表示部分-->  
				  <p class="image"><%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "100x100", class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></p>  
					  <div class="name">
							<p>name</p>
							<p><%= @user.name %></p>
					  </div>	
					  <div class="introduction">
							<p>Introduction</p>	
							<p><%= @user.introduction %></p>
					  </div>			
			  <!--プロフィール編集画面リンク-->
					<% if @user.id == current_user.id %>
						<%= link_to edit_user_path(@user) do %>
							<i class="col-xs-12 btn btn-default glyphicon glyphicon-wrench"></i>
						<% end %>
					<% else %>
						<%= link_to user_path(current_user) do %>
							<i class="col-xs-12 btn btn-default glyphicon glyphicon-wrench"></i>
						<% end %>	
					<% end %>
	<!--ここまで-->
	<!--投稿画面-->
					<h2>New book</h2>
					<!-- form_for部分 -->
					<%= form_for(@book) do |f| %>
						<div class="field">
							<h4>Title</h4>
					<%= f.text_field :title %>
						</div>
						<div class="field">
							<h4>Opinion</h4>
					<%= f.text_area :body %>
						</div>
					<br class="create"><%= f.submit 'Create Book' %></br>
					<% end %>
				</div>
	<!--投稿一覧-->
				<div class="Books col-xs-9">
						<h2 class="Books">Users</h2>
						<table>
							<thead>
								<tr>
									<th class="image">image</th>
									<th class="user-name">name</th>
								</tr>
						</thead>
						<tbody>
							<% @users.each do |user| %>
								<tr class="box-information"> 
									<td><%= attachment_image_tag user, :profile_image, format: 'jpeg', size: "40x40", class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></td>
									<td><%= user.name %></td>					
									<td><%=link_to "Show", user_path(user) %></td>
								</tr>  
							<% end %>
						</tbody> 
					</table>
				</div>
				<!--ここまで-->
			</div>
		</div>
	</div>
</body>

app/views/users/show.html.erb
<body>
	<header>
		<title>Bookers</title>
	</header>
	
	 <div class="body">
	<!--プロフィール画面-->
		<div class="container">
			<div class="row">
				<div class="profiles col-xs-3">
					<h2 class="profile-name">User info</h2>
						  	<!--画像表示部分-->  
				  <p class="picture"><%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "100x100", class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></p>	  
					  <div class="name">	
							<p>name</p>
							<p><%= @user.name %></p>
					  </div>	
					  <div class="introduction">
							<p>Introduction</p>	
							<p><%= @user.introduction %></p>
					  </div>	
			  <!--プロフィール編集画面リンク-->
					<% if @user.id == current_user.id %>
						<%= link_to edit_user_path(@user) do %>
							<i class="col-xs-12 btn btn-default glyphicon glyphicon-wrench"></i>
						<% end %>
					<% else %>
						<%= link_to user_path(current_user) do %>
							<i class="col-xs-12 btn btn-default glyphicon glyphicon-wrench"></i>
						<% end %>	
					<% end %>
	<!--ここまで-->
	<!--投稿画面-->
				<h2>New book</h2>
				<!-- form_for部分 -->
				<%= form_for(@book) do |f| %>
					<div class="field">
						<h4>Title</h4>
				<%= f.text_field :title %>
					</div>
					<div class="field">
						<h4>Opinion</h4>
				<%= f.text_area :body %>
					</div>
				<br class="create"><%= f.submit 'Create Book' %></br>
				<% end %>
			</div>
<!--ここまで-->
<!--本一覧画面-->
				<div class="Books col-xs-9">
					<h2 class="Users">Books</h2>
					<table>
						<thead>
							<tr>
								<th class="title">Title</th>
								<th class="opinion">Opinion</th>
							</tr>
						</thead>
						<tbody>
							<% @books.each do |book| %>
								<tr class="book-information"> 			
									<td><%= attachment_image_tag book.user, :profile_image, format: 'jpeg', size: "40x40", class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></td>
									<td><%=link_to book.title, book_path(book) %></td>　　　
									<td><%= book.body %></td>
								</tr>  
							<% end %>
						</tbody> 
					</table>
				</div>
			<!--ここまで-->
			</div>
		</div>
	</div>
</body>